################################################################################
# Brain clock: merge all expression matrixes and metDat files generated by     #
# lincs_parse.R in a single expMat file and a single metDat file.              #
################################################################################
if(!require(argparser, quietly = T)){
        install.packages("argparser", repos='http://cran.us.r-project.org')
}
library(argparser)

# Terminal argument parser
################################################################################
parser <- arg_parser("Merge parsed expMat or metDat DFs in a single file.")

parser <- add_argument(parser = parser,
                       arg = c("input",
                               "--cellType",
                               "--whichDF",
                               "--outDir"),
                       help = c("Directory where the parsed files are.",
                                "Desired cell type.",
                                "Either if expression (expMat) or metadata (metDat) matrices should be concatenated.",
                                "Output directory where placing the results."),
                       flag = c(F, F, F, F))

parsed <- parse_args(parser)

# Directory stuff
################################################################################

matDir <- "/mnt/lscratch/users/gsantamaria/test_large_files/NPC/parsed_mats/"
cellType <- "NPC"
whichDF <- "metDat"
outDir <- "/mnt/lscratch/users/gsantamaria/test_large_files/NPC/parsed_mats/"


matDir <- parsed$input
cellType <- parsed$cellType
whichDF <- parsed$whichDF
outDir <- parsed$outDir

outName <- sprintf("%slincs_%s_concat_%s.csv",
                   outDir,
                   cellType,
                   whichDF)

listFiles <- list.files(matDir, full.names = T)

targetFiles <- listFiles[grep(sprintf("%s.csv", whichDF), listFiles)]
targetFiles <- targetFiles[!grepl(sprintf("concat_%s.csv", whichDF),
                                  targetFiles)]

# Functions
################################################################################

# read.csv but faster
readCsvFst <- function(pth, header = T){
        df <- data.frame(data.table::fread(pth, header = header))
        rownames(df) <- df$V1
        df <- df[, colnames(df) != "V1"]
        return(df)
}

# write.csv, but faster
writeCsvFst <- function(df, file, rowNames = T, colNames = T){
        if(rowNames){
                rn <- rownames(df)
                df <- data.table::data.table(df)
                df[, V1 := rn]
                data.table::setcolorder(df, c("V1", setdiff(names(df), "V1")))
        }else{
                df <- data.table::data.table(df)
        }
        data.table::fwrite(df, file, col.names = colNames)
}

# Given a list of csv files, concatenates them either row wise or column wise
concatFileList <- function(file_list, concatBy){
        outDF <- NULL
        #file_list <- targetFiles
        #concatBy <- "rows"
        for(i in seq_along(file_list)){
                #i <- 5
                f <- file_list[i]
                df <- readCsvFst(f)
                # In the case of metDat, the control files have less columns,
                # so let's add them filled by NAs
                if(concatBy == "rows" & !is.null(outDF)){
                        cols2Add <- colnames(outDF)[!colnames(outDF) %in% colnames(df)]
                        cols2BindDF <- data.frame(matrix(nrow = nrow(df),
                                                         ncol = length(cols2Add),
                                                         dimnames = list(rownames(df),
                                                                         cols2Add)))
                        df <- cbind.data.frame(df, cols2BindDF)
                        df <- df[, colnames(outDF)]
                }
                if(is.null(outDF)){
                        outDF <- df
                }else{
                        if(concatBy == "cols"){
                                outDF <- cbind.data.frame(outDF, df)
                        }else if(concatBy == "rows"){
                                outDF <- rbind.data.frame(outDF, df)
                        }
                }
        }
        return(outDF)
}

# Concatenate files
################################################################################

print(sprintf("Concatenating %s matrices...", whichDF))
if(whichDF == "expMat"){
        conc <- concatFileList(targetFiles,
                               concatBy = "cols")
}else if (whichDF == "metDat"){
        conc <- concatFileList(targetFiles,
                               concatBy = "rows")
}

writeCsvFst(conc, file = outName)
print(sprintf("%s saved at %s.", basename(outName), dirname(outName)))
