################################################################################
# Brain clock: quantile normalize the merged perturbation dataset, using as    #
# target distribution the extracted from the clinical dataset. It is possible  #
# to restrict it to only the train set, by providing a dataset indicating the  #
# train-test division, generated by train_test_split.R.                        #
################################################################################

if(!require("plotUtils", quietly = T)){
        devtools::install_github('guisantagui/plotUtils', upgrade = "never")
}
if (!require("preprocessCore", quietly = T)){
        BiocManager::install("preprocessCore", configure.args=c(preprocessCore = "--disable-threading"),
                             update = F)
}
library(preprocessCore)
library(plotUtils)
library(argparser)

# Terminal argument parser
################################################################################
parser <- arg_parser("Quantile-normalize perturbation data, optionally being able to provide a train_test dataframe so only training set is used for determining the distribution.")

parser <- add_argument(parser = parser,
                       arg = "input",
                       help = "Perturbation expression matrix.",
                       flag = F)

parser <- add_argument(parser = parser,
                       arg = "--metDat",
                       help = "Metadata matrix of the perturbation data.",
                       flag = F,
                       default = NA)

parser <- add_argument(parser = parser,
                       arg = "--clin_dat",
                       help = "Clinical data expression matrix, to be used as a reference.",
                       flag = F,
                       default = NA)

parser <- add_argument(parser = parser,
                       arg = "--train_test",
                       help = "A file of train/test assignments. Generated with train_test_split.R",
                       flag = F,
                       default = NA)

parsed <- parse_args(parser)

# Directory stuff
################################################################################
perts_f <- "/home/users/gsantamaria/projects/brain_clock/results/parsed/merged_perts/merged_perts_exprsn.csv"
metDat_f <- "/home/users/gsantamaria/projects/brain_clock/results/parsed/merged_perts/merged_perts_metdat.csv"
clin_f <- "/home/users/gsantamaria/projects/brain_clock/results/preproc/second_round/merged_counts_mod_alpha1_coefs_log2_qnorm_noCerebell_onlyAge_svaAdj.csv"
train_test_f <- "/home/users/gsantamaria/projects/brain_clock/results/parsed/merged/train_test.csv"

clin_f <- NA
train_test_f <- NA

perts_f <- parsed$input
metDat_f <- parsed$metDat
clin_f <- parsed$clin_dat
train_test_f <- parsed$train_test

# Load data
################################################################################
perts <- read_table_fast(perts_f, row.names = 1)
if (!is.na(clin_f)){
        clin <- read_table_fast(clin_f, row.names = 1)
}
if (!is.na(metDat_f)){
        metDat <- read_table_fast(metDat_f, row.names = 1)
}



# Quantile-normalized merged dataset
################################################################################

if (exists("clin")){
        # If clinical data was provided, use it as a reference

        # Keep only genes in perts that are in clin
        perts <- perts[, match(colnames(clin), colnames(perts))]


        # Obtain target distribution from clinical data
        Sys.setenv(OMP_NUM_THREADS = "1")

        if (!is.na(train_test_f) && file.exists(train_test_f)){
                print(sprintf("Using as normalization reference the one extracted from the training samples in %s, as indicated in %s...", clin_f, train_test_f))
                train_test <- read_table_fast(train_test_f, row.names = 1)
                train_samps <- make.names(train_test$specimenID[train_test$train_test_split == "train"])
                clin_train <- clin[make.names(rownames(clin)) %in% train_samps, ]
                target_dist <- normalize.quantiles.determine.target(t(clin_train))
        }else{
                print(sprintf("Using as normalization reference the one extracted from all the samples in %s...", clin_f))
                target_dist <- normalize.quantiles.determine.target(t(clin))
        }
        outPath_quantNorm <- gsub(".csv", "_clinRef_qnorm.csv", perts_f)
}else if(!exists("clin") & exists("metDat")){
        print(sprintf("Quantile-normalizing using the whole %s matrix...", basename(perts_f)))
        # If clinical data was not provided, and metadata exists, separate perturbation compendium
        # from LINCS, and apply distribution from LINCS to perturbation compendium.

        # Plot the distribution of only LINCS
        lincsSamps <- make.names(metDat$specimenID[metDat$substudy == "LINCS"])
        pdf(file = sprintf("%s/lincs_before_distr.pdf", dirname(perts_f)))
        plot(density(as.matrix(perts[rownames(perts) %in% lincsSamps, ])))
        dev.off()

        # Store rownames of the whole dataframe
        all_rnames <- rownames(perts)
        # Obtain a sub-dataset of the perturbations that are not LINCS
        p111Samps <- make.names(metDat$specimenID[metDat$substudy == "perts_111"])
        perts_p111 <- perts[rownames(perts) %in% p111Samps, ]
        # Log2 transform
        perts_p111 <- log2(perts_p111 + 1)
        perts <- rbind.data.frame(perts[rownames(perts) %in% lincsSamps, ],
                                  perts_p111)
        # Reorder rows (just in case)
        perts <- perts[match(all_rnames, rownames(perts)), ]
        # Plot again, but with all
        pdf(file = sprintf("%s/perts_before_distr.pdf", dirname(perts_f)))
        plot(density(as.matrix(perts)))
        dev.off()
        target_dist <- normalize.quantiles.determine.target(t(perts))
        outPath_quantNorm <- gsub(".csv", "_log2111_qnorm.csv", perts_f)
}

perts <- t(perts)
perts_quantNorm <- normalize.quantiles.use.target(as.matrix(perts),
                                                  target_dist)
# Reassign the dimnames, as normalize.quantiles removes them
dimnames(perts_quantNorm) <- dimnames(perts)
perts_quantNorm <- t(perts_quantNorm)

write_table_fast(perts_quantNorm, f = outPath_quantNorm)
print(sprintf("%s saved at %s.",
              basename(outPath_quantNorm),
              dirname(outPath_quantNorm)))