################################################################################
# Brain Clock: Examine the perturbation statistics file generated by           #
# model_pert_stats.R to determine what are the significantly rejuvenating      #
# compounds per cell type and what are their mechanisms of action.             #
################################################################################

if(!require(ggplot2)){
        install.packages("ggplot2", repos='http://cran.us.r-project.org')
}
if(!require(devtools)){
        install.packages("devtools", repos='http://cran.us.r-project.org')
}
if (!require(plotUtils, quietly = T)){
        devtools::install_github("guisantagui/plotUtils", upgrade = "never")
}
library(plotUtils)
library(argparser)
library(ggplot2)

# Functions
################################################################################

do_moa_ORA <- function(drug_vec, drug_metDat){
        #drug_vec <- rejuvDrugs_NPC$drug
        #drug_metDat <- drugMetDat
        moas <- unique(drug_metDat$moa)
        drug_metDat_noTarg <- drug_metDat[!drug_metDat$pert_name %in% drug_vec, ]
        moa_pVals <- c()
        drugs_in_moa <- c()
        n_in_moa <- c()
        enrich_ratios <- c()
        for(moa in moas){
                #moa <- moas[1]
                drugs_moa <- drug_metDat$moa[match(drug_vec,
                                                   drug_metDat$pert_name)]
                names(drugs_moa) <- drug_vec
                drugs_moa[is.na(drugs_moa)] <- "-"
                drugNames_moa <- paste(names(drugs_moa)[drugs_moa == moa], collapse = ";")
                if (drugNames_moa == ""){
                        drugNames_moa <- NA
                }
                drugs_in_moa <- c(drugs_in_moa, drugNames_moa)
                drugs_moa <- sum(drugs_moa == moa)
                drugs_not_moa <- length(drug_vec) - drugs_moa
                drugs_all_moa <- sum(drug_metDat_noTarg$moa == moa)
                drugs_all_not_moa <- nrow(drug_metDat_noTarg) - drugs_all_moa
                cont <- matrix(c(drugs_moa, drugs_all_moa, drugs_not_moa, drugs_all_not_moa), nrow = 2)
                fish_pVal <- fisher.test(cont, alternative = "greater")$p.value
                moa_pVals <- c(moa_pVals, fish_pVal)
                n_in_moa <- c(n_in_moa, drugs_moa)
                enrich_ratios <- c(enrich_ratios, drugs_moa/sum(drug_metDat$moa == moa))
        }
        outDF <- data.frame(moa = moas,
                            pVal = moa_pVals,
                            pAdj = p.adjust(moa_pVals, method = "BH"),
                            n_enrich = n_in_moa,
                            enrich_ratio = enrich_ratios,
                            drugs_in_moa = drugs_in_moa)
        return(outDF)
}

moa_ora_dotplot <- function(oraDF, alph,
                            sort_by, topN = NULL){
        plot_df <- oraDF[oraDF$pAdj <= alph, ]
        if (sort_by == "enrich_ratio"){
                plot_df <- plot_df[order(plot_df$enrich_ratio, decreasing = F), ]
        }else if (sort_by == "p_value"){
                plot_df <- plot_df[order(plot_df$pAdj, decreasing = T), ]
        }
        if (!is.null(topN) && topN < nrow(plot_df)){
                plot_df <- plot_df[1:topN, ]
        }
        plot_df$moa <- factor(plot_df$moa, levels = plot_df$moa)
        plt <- ggplot(plot_df, mapping = aes(x = moa, y = enrich_ratio,
                                             color = pAdj,
                                             size = n_enrich)) +
                geom_point() + 
                scale_size(range = c(2, 10)) +
                labs(x = "MOA", y = "enrichment ratio",
                     color = "FDR",
                     size = "n. of drugs in MOA") +
                scale_color_gradient(low = "red", high = "blue") +
                guides(fill = guide_colorbar(reverse = TRUE)) +
                coord_flip() +
                scale_y_continuous(expand = expansion(mult = c(0.2, 0.2))) +
                theme(axis.text.y = element_text(size=15),
                      axis.text.x = element_text(size=15),
                      axis.title.x = element_text(size=18),
                      axis.title.y = element_blank(),
                      title = element_text(size=20),
                      panel.background = element_blank(),
                      panel.grid.major = element_line(colour = "gray"),
                      panel.grid.minor = element_blank(),
                      legend.text = element_text(size=12),
                      legend.title = element_text(size=13),
                      axis.line = element_line(colour = "black"),
                      axis.line.y = element_line(colour = "black"),
                      panel.border = element_rect(colour = "black",
                                                  fill=NA,
                                                  linewidth = 1))
        return(plt)
}

# Terminal argument parser
################################################################################
parser <- arg_parser("Train the GLM on transformed age and assess performance.")

parser <- add_argument(parser = parser,
                       arg = c("input",
                               "--alpha",
                               "--what_test",
                               "--lincs_drugs"),
                       help = c("Stats of the comparisons of predicted ages (generated with model_pert_stats.R).",
                                "Significance level for the filtering",
                                "What p-values to use in the comparisons. t.test or wilcox.test",
                                "Metadata of the compounds in LINCS L1000"),
                       flag = c(F,
                                F,
                                F,
                                F))

parsed <- parse_args(parser)

# Directory stuff
################################################################################
pert_stats_f <- "../../results/model_test_perts/pred_ages_stats.csv"
alph <- 0.05
what_test <- "t.test"
lincs_drgs_f <- "../../data/perturbation/lincs/LINCS_small_molecules.tsv"

pert_stats_f <- parsed$input
alph <- as.numeric(parsed$alpha)
what_test <- parsed$what_test
lincs_drgs_f <- parsed$lincs_drugs

outDir <- dirname(pert_stats_f)

# Load data
################################################################################
pert_stats <- read_table_fast(pert_stats_f, row.names = 1)
lincs_drgs <- read_table_fast(lincs_drgs_f, row.names = 1)

# Get significant perturbations
################################################################################
if (what_test == "t.test"){
        stats_col <- "chron_age_tTest_pValAdj"
}else if(what_test == "wilcox.test"){
        stats_col <- "chron_age_wilcox_pValAdj"
}

pert_stats_sign <- pert_stats[pert_stats[, stats_col] <= alph, ]

pert_stats_sign <- pert_stats_sign[pert_stats_sign$chron_age_delta < 0, ]

# Divide by cell type
################################################################################
uniq_cTypes <- unique(pert_stats_sign$cell_type)

for(i in seq_along(uniq_cTypes)){
        cTyp <- uniq_cTypes[i]
        pert_stats_sign_cTyp <- pert_stats_sign[pert_stats_sign$cell_type == cTyp, ]
        # Order by delta to get unique perts ranked by rejuvenating potential
        pert_stats_sign_cTyp <- pert_stats_sign_cTyp[order(pert_stats_sign_cTyp$chron_age_delta), ]
        uniq_perts_cell <- unique(gsub("\\_.*", "", pert_stats_sign_cTyp$perturbation))
        mean_delta <- sapply(uniq_perts_cell,
                             function(x) mean(pert_stats_sign_cTyp$chron_age_delta[grep(x,
                                                                                   pert_stats_sign_cTyp$perturbation)]))
        drug_df <- data.frame(drug = uniq_perts_cell,
                              target = lincs_drgs$target[match(uniq_perts_cell, lincs_drgs$pert_name)],
                              moa = lincs_drgs$moa[match(uniq_perts_cell, lincs_drgs$pert_name)],
                              smiles = lincs_drgs$canonical_smiles[match(uniq_perts_cell, lincs_drgs$pert_name)],
                              inchi_key = lincs_drgs$inchi_key[match(uniq_perts_cell, lincs_drgs$pert_name)],
                              mean_delta = mean_delta)
        write_table_fast(drug_df, f = sprintf("%s/%s_drugs.csv", outDir, cTyp))
        print(sprintf("%s_drugs.csv saved at %s", cTyp, outDir))
        moa_ora_cell <- do_moa_ORA(drug_df$drug, lincs_drgs)
        write_table_fast(moa_ora_cell, f = sprintf("%s/%s_drugs_ora.csv", outDir, cTyp))
        print(sprintf("%s_drugs_ora.csv saved at %s", cTyp, outDir))
        moa_plot_by_ratio <- moa_ora_dotplot(moa_ora_cell, 0.05, sort_by = "enrich_ratio", topN = 20)
        moa_plot_by_pVal <- moa_ora_dotplot(moa_ora_cell, 0.05, sort_by = "p_value", topN = 20)
        ggsave(filename = sprintf("%s/%s_moa_ora_ratio.pdf", outDir, cTyp),  plot = moa_plot_by_ratio, width = 9, height = 8)
        ggsave(filename = sprintf("%s/%s_moa_ora_pval.pdf", outDir, cTyp),  plot = moa_plot_by_pVal, width = 9, height = 8)
}