################################################################################
# Brain Clock: Examine the perturbation statistics file generated by           #
# model_pert_stats.R to determine what are the significantly rejuvenating      #
# compounds per cell type and what are their mechanisms of action.             #
################################################################################

if(!require(devtools)){
        install.packages("devtools", repos='http://cran.us.r-project.org')
}
if (!require(plotUtils, quietly = T)){
        devtools::install_github("guisantagui/plotUtils", upgrade = "never")
}
library(plotUtils)
library(argparser)

# Functions
################################################################################

do_moa_ORA <- function(drug_vec, drug_metDat){
        #drug_vec <- rejuvDrugs_NPC$drug
        #drug_metDat <- drugMetDat
        moas <- unique(drug_metDat$moa)
        drug_metDat_noTarg <- drug_metDat[!drug_metDat$pert_name %in% drug_vec, ]
        moa_pVals <- c()
        drugs_in_moa <- c()
        for(moa in moas){
                #moa <- moas[1]
                drugs_moa <- drug_metDat$moa[match(drug_vec,
                                                   drug_metDat$pert_name)]
                names(drugs_moa) <- drug_vec
                drugs_moa[is.na(drugs_moa)] <- "-"
                drugNames_moa <- paste(names(drugs_moa)[drugs_moa == moa], collapse = ";")
                if (drugNames_moa == ""){
                        drugNames_moa <- NA
                }
                drugs_in_moa <- c(drugs_in_moa, drugNames_moa)
                drugs_moa <- sum(drugs_moa == moa)
                drugs_not_moa <- length(drug_vec) - drugs_moa
                drugs_all_moa <- sum(drug_metDat_noTarg$moa == moa)
                drugs_all_not_moa <- nrow(drug_metDat_noTarg) - drugs_all_moa
                cont <- matrix(c(drugs_moa, drugs_all_moa, drugs_not_moa, drugs_all_not_moa), nrow = 2)
                fish_pVal <- fisher.test(cont, alternative = "greater")$p.value
                moa_pVals <- c(moa_pVals, fish_pVal)
        }
        outDF <- data.frame(moa = moas,
                            pVal = moa_pVals,
                            pAdj = p.adjust(moa_pVals, method = "BH"),
                            drugs_in_moa = drugs_in_moa)
        return(outDF)
}

# Terminal argument parser
################################################################################
parser <- arg_parser("Train the GLM on transformed age and assess performance.")

parser <- add_argument(parser = parser,
                       arg = c("input",
                               "--alpha",
                               "--what_test",
                               "--lincs_drugs"),
                       help = c("Stats of the comparisons of predicted ages (generated with model_pert_stats.R).",
                                "Significance level for the filtering",
                                "What p-values to use in the comparisons. t.test or wilcox.test",
                                "Metadata of the compounds in LINCS L1000"),
                       flag = c(F,
                                F,
                                F,
                                F))

parsed <- parse_args(parser)

# Directory stuff
################################################################################
pert_stats_f <- "/home/users/gsantamaria/projects/brain_clock/results/model_test_perts/mod_first_round_sva_strat_wBSPIext/pred_ages_stats.csv"
alph <- 0.05
what_test <- "t.test"
lincs_drgs_f <- "/home/users/gsantamaria/projects/brain_clock/data/perturbation/lincs/LINCS_small_molecules.tsv"

pert_stats_f <- parsed$input
alph <- as.numeric(parsed$alpha)
what_test <- parsed$what_test
lincs_drgs_f <- parsed$lincs_drugs

outDir <- dirname(pert_stats_f)

# Load data
################################################################################
pert_stats <- read_table_fast(pert_stats_f, row.names = 1)
lincs_drgs <- read_table_fast(lincs_drgs_f, row.names = 1)

# Get significant perturbations
################################################################################
if (what_test == "t.test"){
        stats_col <- "chron_age_tTest_pValAdj"
}else if(what_test == "wilcox.test"){
        stats_col <- "chron_age_wilcox_pValAdj"
}

pert_stats_sign <- pert_stats[pert_stats[, stats_col] <= alph, ]

pert_stats_sign <- pert_stats_sign[pert_stats_sign$chron_age_delta < 0, ]

# Divide by cell type
################################################################################
uniq_cTypes <- unique(pert_stats_sign$cell_type)

for(i in seq_along(uniq_cTypes)){
        cTyp <- uniq_cTypes[i]
        pert_stats_sign_cTyp <- pert_stats_sign[pert_stats_sign$cell_type == cTyp, ]
        uniq_perts_cell <- gsub("\\_.*", "", pert_stats_sign_cTyp$perturbation)
        drug_df <- data.frame(drug = uniq_perts_cell,
                              target = lincs_drgs$target[match(uniq_perts_cell, lincs_drgs$pert_name)],
                              moa = lincs_drgs$moa[match(uniq_perts_cell, lincs_drgs$pert_name)],
                              smiles = lincs_drgs$canonical_smiles[match(uniq_perts_cell, lincs_drgs$pert_name)],
                              inchi_key = lincs_drgs$inchi_key[match(uniq_perts_cell, lincs_drgs$pert_name)])
        write_table_fast(drug_df, f = sprintf("%s/%s_drugs.csv", outDir, cTyp))
        moa_ora_cell <- do_moa_ORA(drug_df$drug, lincs_drgs)
        write_table_fast(moa_ora_cell, f = sprintf("%s/%s_drugs_ora.csv", outDir, cTyp))
}